import = [
  "~/.config/alacritty/themes/catppuccin_macchiato.toml"
]

[window]
title = "Hi Captain!"
opacity = 0.9

[font]
normal = {family = "FiraCode Nerd Font Mono", style = "Regular"}
size = 20

